name: bella-keys-ems

services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      - POSTGRES_USER=${EMS_PG_DB_USER}
      - POSTGRES_PASSWORD=${EMS_PG_DB_PASSWORD}
      - POSTGRES_DB=${EMS_PG_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ems-network

  expense-manager-service:
    build: ./services/expense-manager-service
    container_name: expense-manager-service
    ports:
      - "8000:8000"
    environment:
      - HOST=${EMS_HOST}
      - PORT=${EMS_PORT}
      - DEBUG=${EMS_DEBUG}
      - STORAGE_TYPE=${EMS_STORAGE_TYPE}
      - DATABASE_URL=${EMS_DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ems-network

  keys-personal-assist-ui:
    build: ./keys-personal-assist-ui
    container_name: keys-personal-assist-ui
    ports:
      - "3000:80"
    volumes:
      - ./keys-personal-assist-ui/nginx.ems.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - expense-manager-service
    networks:
      - ems-network

networks:
  ems-network:
    driver: bridge
