"""Make month column as int for easy sort and filter

Revision ID: 14098a210fb7
Revises: 7689120ed8a9
Create Date: 2026-02-01 20:18:27.589486

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14098a210fb7'
down_revision: str | Sequence[str] | None = '7689120ed8a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('month_years', 'month',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="""
               CASE
                   WHEN month ILIKE 'January' THEN 1
                   WHEN month ILIKE 'February' THEN 2
                   WHEN month ILIKE 'March' THEN 3
                   WHEN month ILIKE 'April' THEN 4
                   WHEN month ILIKE 'May' THEN 5
                   WHEN month ILIKE 'June' THEN 6
                   WHEN month ILIKE 'July' THEN 7
                   WHEN month ILIKE 'August' THEN 8
                   WHEN month ILIKE 'September' THEN 9
                   WHEN month ILIKE 'October' THEN 10
                   WHEN month ILIKE 'November' THEN 11
                   WHEN month ILIKE 'December' THEN 12
                   ELSE NULL
               END
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('month_years', 'month',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="""
               CASE
                   WHEN month = 1 THEN 'January'
                   WHEN month = 2 THEN 'February'
                   WHEN month = 3 THEN 'March'
                   WHEN month = 4 THEN 'April'
                   WHEN month = 5 THEN 'May'
                   WHEN month = 6 THEN 'June'
                   WHEN month = 7 THEN 'July'
                   WHEN month = 8 THEN 'August'
                   WHEN month = 9 THEN 'September'
                   WHEN month = 10 THEN 'October'
                   WHEN month = 11 THEN 'November'
                   WHEN month = 12 THEN 'December'
                   ELSE NULL
               END
        """)
    # ### end Alembic commands ###
