"""add_liability_tables

Revision ID: 2c0d5b0b566e
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 15:49:56.496410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c0d5b0b566e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liability_category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liability_category_code'), 'liability_category', ['code'], unique=True)
    op.create_index(op.f('ix_liability_category_name'), 'liability_category', ['name'], unique=True)
    op.create_table('liability_subcategory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('valuation_type', sa.String(), nullable=False),
    sa.Column('has_interest', sa.Boolean(), nullable=False),
    sa.Column('has_maturity', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['liability_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liability_subcategory_category_id'), 'liability_subcategory', ['category_id'], unique=False)
    op.create_index(op.f('ix_liability_subcategory_code'), 'liability_subcategory', ['code'], unique=True)
    op.create_table('liability',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subcategory_id', sa.String(), nullable=True),
    sa.Column('original_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('interest_compounding', sa.String(), nullable=True),
    sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['liability_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['liability_subcategory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liability_category_id'), 'liability', ['category_id'], unique=False)
    op.create_index(op.f('ix_liability_name'), 'liability', ['name'], unique=False)
    op.create_index(op.f('ix_liability_subcategory_id'), 'liability', ['subcategory_id'], unique=False)
    op.create_table('liability_transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('liability_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['liability_id'], ['liability.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liability_transaction_liability_id'), 'liability_transaction', ['liability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liability_transaction_liability_id'), table_name='liability_transaction')
    op.drop_table('liability_transaction')
    op.drop_index(op.f('ix_liability_subcategory_id'), table_name='liability')
    op.drop_index(op.f('ix_liability_name'), table_name='liability')
    op.drop_index(op.f('ix_liability_category_id'), table_name='liability')
    op.drop_table('liability')
    op.drop_index(op.f('ix_liability_subcategory_code'), table_name='liability_subcategory')
    op.drop_index(op.f('ix_liability_subcategory_category_id'), table_name='liability_subcategory')
    op.drop_table('liability_subcategory')
    op.drop_index(op.f('ix_liability_category_name'), table_name='liability_category')
    op.drop_index(op.f('ix_liability_category_code'), table_name='liability_category')
    op.drop_table('liability_category')
    # ### end Alembic commands ###
