"""add_cancellation_to_savings_transaction

Revision ID: 566c9eab4e91
Revises: c85115c31317
Create Date: 2026-05-24 22:42:00.721981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566c9eab4e91'
down_revision: Union[str, Sequence[str], None] = 'c85115c31317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_bucket_transaction', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.execute("UPDATE savings_bucket_transaction SET is_cancelled = FALSE")
    op.alter_column('savings_bucket_transaction', 'is_cancelled', nullable=False)
    op.add_column('savings_bucket_transaction', sa.Column('cancellation_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_bucket_transaction', 'cancellation_reason')
    op.drop_column('savings_bucket_transaction', 'is_cancelled')
    # ### end Alembic commands ###
