"""initial version of database for expense manager service

Revision ID: 7689120ed8a9
Revises: 
Create Date: 2025-12-30 12:28:57.713432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7689120ed8a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_name'), 'accounts', ['account_name'], unique=True)
    op.create_table('month_years',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_month_year')
    )
    op.create_index(op.f('ix_month_years_month'), 'month_years', ['month'], unique=False)
    op.create_index(op.f('ix_month_years_year'), 'month_years', ['year'], unique=False)
    op.create_table('spending_account_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('date_detail_id', sa.String(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('current_credit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['date_detail_id'], ['month_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date_detail_id', name='uq_account_date_detail')
    )
    op.create_index(op.f('ix_spending_account_entries_account_id'), 'spending_account_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_spending_account_entries_date_detail_id'), 'spending_account_entries', ['date_detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spending_account_entries_date_detail_id'), table_name='spending_account_entries')
    op.drop_index(op.f('ix_spending_account_entries_account_id'), table_name='spending_account_entries')
    op.drop_table('spending_account_entries')
    op.drop_index(op.f('ix_month_years_year'), table_name='month_years')
    op.drop_index(op.f('ix_month_years_month'), table_name='month_years')
    op.drop_table('month_years')
    op.drop_index(op.f('ix_accounts_account_name'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
