"""add_emi_start_date

Revision ID: a7f8b25dd8b5
Revises: be76aa1ded1a
Create Date: 2026-06-21 22:42:04.482864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a7f8b25dd8b5'
down_revision: Union[str, Sequence[str], None] = 'be76aa1ded1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liability', sa.Column('emi_start_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liability', 'emi_start_date')
    # ### end Alembic commands ###
