"""add_emi_amount_to_liability

Revision ID: be76aa1ded1a
Revises: 2c0d5b0b566e
Create Date: 2026-06-21 16:18:03.974371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'be76aa1ded1a'
down_revision: Union[str, Sequence[str], None] = '2c0d5b0b566e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liability', sa.Column('emi_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liability', 'emi_amount')
    # ### end Alembic commands ###
