"""add_savings_buckets_tables

Revision ID: c85115c31317
Revises: b73d1f3e4c21
Create Date: 2026-05-24 03:24:53.248171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85115c31317'
down_revision: Union[str, Sequence[str], None] = 'b73d1f3e4c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_bucket',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('allocated_amount', sa.Float(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_account_bucket_name')
    )
    op.create_index(op.f('ix_savings_bucket_account_id'), 'savings_bucket', ['account_id'], unique=False)
    op.create_table('savings_bucket_transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('source_bucket_id', sa.String(), nullable=True),
    sa.Column('destination_bucket_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_bucket_id'], ['savings_bucket.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_bucket_id'], ['savings_bucket.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_bucket_transaction_account_id'), 'savings_bucket_transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_savings_bucket_transaction_destination_bucket_id'), 'savings_bucket_transaction', ['destination_bucket_id'], unique=False)
    op.create_index(op.f('ix_savings_bucket_transaction_source_bucket_id'), 'savings_bucket_transaction', ['source_bucket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_bucket_transaction_source_bucket_id'), table_name='savings_bucket_transaction')
    op.drop_index(op.f('ix_savings_bucket_transaction_destination_bucket_id'), table_name='savings_bucket_transaction')
    op.drop_index(op.f('ix_savings_bucket_transaction_account_id'), table_name='savings_bucket_transaction')
    op.drop_table('savings_bucket_transaction')
    op.drop_index(op.f('ix_savings_bucket_account_id'), table_name='savings_bucket')
    op.drop_table('savings_bucket')
    # ### end Alembic commands ###
