name: expense-manager-service

services:

  expense-manager-service:
    build: .
    container_name: expense-manager-service
    ports:
      - "8000:8000"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - PG_DB_HOST=${PG_DB_HOST}
    networks:
      - expense-manager-network

networks:
  expense-manager-network:
    driver: bridge
