[pytest]
testpaths = tests
asyncio_mode = auto
addopts =
    -vv
    -s
    --cov-config=.coveragerc
    --cov=app/ tests/
    --cov-report=html
markers =
    unit: marks tests as unit tests
    integration: marks tests as integration tests
